export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const SET_USER_DATA_SUCCESS = "SET_USER_DATA_SUCCESS";
export const SET_USER_DATA_ERROR = "SET_USER_DATA_ERROR";


